version: '3'
services:
  presentation:
    build: .
    networks: 
      - kubeadm-dind-net
    privileged: true
    ports:
      - 3000:3000
    hostname: server
    environment:
      - MODE=prod
      - PASSWORD=dummy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  kubeadm-dind-net:
    external: true
