version: '3'
services:
  presentation:
    build: .
    networks: 
      - kubeadm-dind-net
      - core
    privileged: true
    hostname: server
    environment:
      - MODE=prod
      - PASSWORD=${PASSWORD}
    labels:
      - traefik.port=3000
      - traefik.frontend.rule=Host:presentation.fredriklowenhamn.se
      - traefik.enable=true
      - traefik.docker.network=core
   
  proxy:
    image: lowet84/port-forward
    environment:
      - FROM=8080
      - TO=30080
      - HOST=kube-node-1
    networks:
     - kubeadm-dind-net
     - core
    labels:
     - traefik.port=8080
     - traefik.frontend.rule=Host:k8sdemo.duckdns.org
     - traefik.enable=true
     - traefik.docker.network=core

networks:
  kubeadm-dind-net:
    external: true
  core:
    external: true
