apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  rules:
  - host: elevate.se
    http:
      paths:
      - backend:
          serviceName: demo-service
          servicePort: 3000
